var extid = chrome.runtime.id;
var doc = document.head || document.body;
//doc.setAttribute("data-superwebrequest-id", extid);
var meta=document.createElement("meta");
meta.setAttribute("name","superwebrequestid");
meta.setAttribute("content",extid);
doc.appendChild(meta);
meta=document.createElement("meta");
meta.setAttribute("name","superwebrequestver");
meta.setAttribute("content",chrome.runtime.getManifest().version);
doc.appendChild(meta);